# Generated by Django 5.2.17 on 2026-09-14 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0003_bucket_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('normalized_part_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('provider_diagram_id', models.CharField(max_length=200)),
                ('diagram_code', models.CharField(blank=True, max_length=200)),
                ('source_image_url', models.URLField(blank=True, max_length=1000)),
                ('license_status', models.CharField(choices=[('EXTERNAL_REFERENCE_ONLY', 'External reference only'), ('LOCALLY_STORED', 'Locally stored')], default='EXTERNAL_REFERENCE_ONLY', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.fileobject')),
            ],
            options={
                'ordering': ['provider', 'diagram_code'],
            },
        ),
        migrations.CreateModel(
            name='DiagramPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callout', models.CharField(blank=True, max_length=50)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_parts', to='catalogue_storage.diagram')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_parts', to='catalogue_storage.oempart')),
            ],
            options={
                'ordering': ['diagram', 'callout'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagram',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_diagram_id'), name='unique_diagram_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='diagrampart',
            constraint=models.UniqueConstraint(fields=('diagram', 'part'), name='unique_part_per_diagram'),
        ),
    ]
