# Generated by Django 5.2.17 on 2026-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_storage', '0002_seed_spare_parts_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='oempart',
            name='applicability',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='oempart',
            name='fitment_notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
