# Generated by Django 5.2.17 on 2026-08-21 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databases', '0002_connecteddatabase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboards_created', to=settings.AUTH_USER_MODEL)),
                ('tenant_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='databases.tenantdatabase')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_database', 'name'), name='unique_dashboard_name_per_database')],
            },
        ),
    ]
