# Generated by Django 5.2.17 on 2026-08-09 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('varchar', 'Varchar'), ('integer', 'Integer'), ('bigint', 'Big Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('uuid', 'UUID'), ('json', 'JSON')], max_length=20)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('scale', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField(default=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DBTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DBIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=63, unique=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.ManyToManyField(related_name='indexes', to='databases.dbcolumn')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='databases.dbtable')),
            ],
        ),
        migrations.CreateModel(
            name='DBForeignKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_delete', models.CharField(choices=[('cascade', 'Cascade'), ('restrict', 'Restrict'), ('set_null', 'Set Null')], default='restrict', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key', to='databases.dbcolumn')),
                ('references_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_fk', to='databases.dbcolumn')),
                ('references_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='databases.dbtable')),
            ],
        ),
        migrations.AddField(
            model_name='dbcolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='databases.dbtable'),
        ),
        migrations.CreateModel(
            name='TenantDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('schema_name', models.CharField(editable=False, max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_databases_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_databases', to='workspaces.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dbtable',
            name='tenant_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='databases.tenantdatabase'),
        ),
        migrations.AddConstraint(
            model_name='dbcolumn',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='unique_column_name_per_table'),
        ),
        migrations.AddConstraint(
            model_name='tenantdatabase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_tenant_database_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='dbtable',
            constraint=models.UniqueConstraint(fields=('tenant_database', 'name'), name='unique_table_name_per_database'),
        ),
    ]
