# Generated by Django 5.2.17 on 2026-08-09 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL')], default='postgresql', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('database_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('encrypted_password', models.BinaryField()),
                ('sslmode', models.CharField(choices=[('disable', 'Disable'), ('prefer', 'Prefer'), ('require', 'Require'), ('verify-full', 'Verify Full')], default='require', max_length=20)),
                ('status', models.CharField(choices=[('untested', 'Untested'), ('connected', 'Connected'), ('unreachable', 'Unreachable')], default='untested', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_databases_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_databases', to='workspaces.project')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_connected_database_name_per_project')],
            },
        ),
    ]
