import uuid

from django.conf import settings
from django.db import models


class Application(models.Model):
    """A registered piece of software, owned by an Organization, with an
    owning User (docs/architecture/DATA_MODEL.md Section 3.7)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(
        "organizations.Organization", on_delete=models.CASCADE, related_name="applications"
    )
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="applications_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["organization", "name"], name="unique_application_name_per_org"),
        ]
        ordering = ["name"]

    def __str__(self):
        return self.name


class ServiceAccount(models.Model):
    """The identity an Application authenticates as. Deliberately backed
    by a real `accounts.User` row (`identity_user`, unusable password —
    it can never log into the web UI) rather than a parallel principal
    type: every existing permission check, RoleAssignment, ResourceGrant,
    and tenant-membership lookup already works in terms of `User`, and
    duplicating that machinery for a second principal type would be a
    second, easy-to-miss place for the isolation invariants in
    docs/security/THREAT_MODEL.md Section 4 to be re-implemented (and
    potentially get wrong). A Membership row (created alongside this one,
    see applications/services.py) makes the identity_user resolvable by
    every existing get_member_* helper; Membership alone grants no
    permissions, so this doesn't widen access — only RoleAssignment/
    ResourceGrant do that, exactly as for a human user."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    application = models.OneToOneField(Application, on_delete=models.CASCADE, related_name="service_account")
    identity_user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="service_account"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"service account for {self.application}"

    @property
    def organization_id(self):
        return self.application.organization_id


class ApplicationCredential(models.Model):
    """Never stores the plaintext secret — only its SHA-256 hash (fast
    hash, not a slow password hasher: the secret is a high-entropy random
    token generated by the server, not a user-chosen password, so brute-
    force/rainbow-table resistance from a slow hash isn't the relevant
    property here — Section 13 of the master prompt: never store
    plaintext long-term secrets when a secure hash is sufficient). The
    plaintext is returned exactly once, at creation/rotation time, by
    applications/services.py — never persisted, never logged."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    service_account = models.ForeignKey(
        ServiceAccount, on_delete=models.CASCADE, related_name="credentials"
    )
    # Nullable for backward compatibility with credentials issued before
    # Environment existed, and because an Application-level credential
    # with no environment at all remains a valid, supported shape (not
    # every integration needs per-environment scoping). When set, this
    # credential's access to any Environment-bound resource (a
    # TenantDatabase/Bucket whose own `environment` FK is set) is
    # restricted to that exact Environment -- enforced in
    # environments.services.check_environment_scope, called from
    # databases/storage's row/file views. A credential with
    # environment=None is unrestricted by this specific check (existing
    # behavior, unchanged) but still subject to every ResourceGrant/Role
    # check exactly as before.
    environment = models.ForeignKey(
        "environments.Environment",
        on_delete=models.SET_NULL,
        related_name="credentials",
        null=True,
        blank=True,
    )
    secret_hash = models.CharField(max_length=64, unique=True)  # hex sha256
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="application_credentials_created",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"credential {self.id} for {self.service_account}"

    @property
    def organization_id(self):
        return self.service_account.organization_id
