# Generated by Django 5.2.17 on 2026-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('control_db', 'Control-Plane Database'), ('tenant_db', 'Tenant Database'), ('object_storage', 'Object Storage'), ('configuration', 'Configuration')], max_length=20),
        ),
    ]
