# Generated by Django 5.2.17 on 2026-08-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcredential',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='environments.environment'),
        ),
    ]
