from django.urls import path

from . import views

urlpatterns = [
    path(
        "applications/<uuid:application_id>/environments/",
        views.EnvironmentListCreateView.as_view(),
        name="environment-list-create",
    ),
    path(
        "environments/<uuid:environment_id>/",
        views.EnvironmentDetailView.as_view(),
        name="environment-detail",
    ),
    path(
        "environments/<uuid:environment_id>/clone/",
        views.EnvironmentCloneView.as_view(),
        name="environment-clone",
    ),
    path(
        "environments/<uuid:environment_id>/disable/",
        views.EnvironmentDisableView.as_view(),
        name="environment-disable",
    ),
    path(
        "environments/<uuid:environment_id>/enable/",
        views.EnvironmentEnableView.as_view(),
        name="environment-enable",
    ),
    path(
        "environments/<uuid:environment_id>/variables/",
        views.EnvironmentVariableListCreateView.as_view(),
        name="environment-variable-list-create",
    ),
    path(
        "environments/<uuid:environment_id>/variables/<uuid:variable_id>/",
        views.EnvironmentVariableDetailView.as_view(),
        name="environment-variable-detail",
    ),
    path(
        "environments/<uuid:environment_id>/secrets/",
        views.EnvironmentSecretListCreateView.as_view(),
        name="environment-secret-list-create",
    ),
    path(
        "environments/<uuid:environment_id>/secrets/<uuid:secret_id>/",
        views.EnvironmentSecretDetailView.as_view(),
        name="environment-secret-detail",
    ),
    path(
        "environments/<uuid:environment_id>/secrets/<uuid:secret_id>/rotate/",
        views.EnvironmentSecretRotateView.as_view(),
        name="environment-secret-rotate",
    ),
    path(
        "environments/<uuid:environment_id>/webhooks/",
        views.EnvironmentWebhookListCreateView.as_view(),
        name="environment-webhook-list-create",
    ),
    path(
        "environments/<uuid:environment_id>/webhooks/<uuid:webhook_id>/",
        views.EnvironmentWebhookDetailView.as_view(),
        name="environment-webhook-detail",
    ),
    path(
        "environments/<uuid:environment_id>/database/",
        views.EnvironmentDatabaseBindingView.as_view(),
        name="environment-database-binding",
    ),
    path(
        "environments/<uuid:environment_id>/storage/",
        views.EnvironmentStorageBindingView.as_view(),
        name="environment-storage-binding",
    ),
    path(
        "environments/<uuid:environment_id>/credentials/",
        views.EnvironmentCredentialListCreateView.as_view(),
        name="environment-credential-list-create",
    ),
    path(
        "environments/<uuid:environment_id>/credentials/<uuid:credential_id>/revoke/",
        views.EnvironmentCredentialRevokeView.as_view(),
        name="environment-credential-revoke",
    ),
    path(
        "environments/<uuid:environment_id>/credentials/<uuid:credential_id>/rotate/",
        views.EnvironmentCredentialRotateView.as_view(),
        name="environment-credential-rotate",
    ),
]
