# Generated by Django 5.2.17 on 2026-08-08 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='workspaces.project'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.bucket'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storage.fileobject'),
        ),
        migrations.AddField(
            model_name='folder',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='storage.bucket'),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.folder'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.folder'),
        ),
        migrations.AddConstraint(
            model_name='bucket',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_bucket_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('bucket', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['bucket', 'status'], name='storage_fil_bucket__bde8c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bucket', 'folder', 'display_filename'), name='unique_active_filename_per_folder'),
        ),
    ]
