# Generated by Django 5.2.17 on 2026-08-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='environment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bucket', to='environments.environment'),
        ),
    ]
