# Generated by Django 5.2.17 on 2026-09-08 14:20

import app_platform.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_external_sharing_enabled'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('draft', models.JSONField(default=app_platform.models.empty_definition)),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app_platform.apptemplate')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_instances', to='workspaces.project')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_platform.apptemplateversion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=63)),
                ('source_definition_id', models.UUIDField(editable=False, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app_platform.appinstance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=63)),
                ('source_definition_id', models.UUIDField(editable=False, null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app_platform.modeldefinition')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=63)),
                ('source_definition_id', models.UUIDField(editable=False, null=True)),
                ('kind', models.CharField(default='many_to_one', max_length=20)),
                ('deletion_policy', models.CharField(default='restrict', max_length=20)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='app_platform.appinstance')),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='app_platform.modeldefinition')),
                ('target_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='app_platform.modeldefinition')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='apptemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='app_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='apptemplateversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='app_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='modeldefinition',
            constraint=models.UniqueConstraint(fields=('instance', 'key'), name='app_model_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='modeldefinition',
            constraint=models.UniqueConstraint(fields=('instance', 'source_definition_id'), name='app_model_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('model', 'key'), name='app_field_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('model', 'source_definition_id'), name='app_field_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.CheckConstraint(condition=models.Q(('data_type__in', ['text', 'integer', 'decimal', 'boolean', 'date', 'datetime'])), name='app_field_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='relationshipdefinition',
            constraint=models.UniqueConstraint(fields=('instance', 'key'), name='app_relationship_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='relationshipdefinition',
            constraint=models.UniqueConstraint(fields=('instance', 'source_definition_id'), name='app_relation_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='relationshipdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'many_to_one')), name='app_relation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='relationshipdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('deletion_policy__in', ['restrict', 'set_null'])), name='app_relation_delete_valid'),
        ),
    ]
