# Generated by Django 5.2.17 on 2026-09-09 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0002_definition_guards'),
        ('databases', '0003_tenantdatabase_environment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeProvision',
            fields=[
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='runtime_provision', serialize=False, to='app_platform.appinstance')),
                ('plan', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('bindings', models.JSONField(default=dict)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('database', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_runtime', to='databases.tenantdatabase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('database__isnull', True)), models.Q(('completed_at__isnull', False), ('database__isnull', False)), _connector='OR'), name='app_runtime_completion_consistent')],
            },
        ),
    ]
