# Generated by Django 5.2.17 on 2026-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0005_recordattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielddefinition',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='modeldefinition',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='relationshipdefinition',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='default_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationshipdefinition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
