# Generated by Django 5.2.17 on 2026-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0007_schema_evolution_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
