# Generated by Django 5.2.17 on 2026-09-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0009_field_index_unique_guards'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationshipdefinition',
            name='app_relation_kind_valid',
        ),
        migrations.AddConstraint(
            model_name='relationshipdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['many_to_one', 'many_to_many'])), name='app_relation_kind_valid'),
        ),
    ]
