# Generated by Django 5.2.17 on 2026-09-11 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0010_many_to_many_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=63)),
                ('source_definition_id', models.UUIDField(editable=False, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('fields', models.ManyToManyField(related_name='unique_constraints', to='app_platform.fielddefinition')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='app_platform.modeldefinition')),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('model', 'key'), name='app_constraint_key_unique'), models.UniqueConstraint(fields=('model', 'source_definition_id'), name='app_constraint_source_unique')],
            },
        ),
    ]
