# Generated by Django 5.2.17 on 2026-08-09 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('error', 'Error')], max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='audit_audit_organiz_c9cbc6_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_17d98a_idx')],
            },
        ),
    ]
