# Generated by Django 5.2.17 on 2026-08-21 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0002_organization_external_sharing_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'action', '-timestamp'], name='audit_audit_organiz_353e66_idx'),
        ),
    ]
