# Generated by Django 5.2.17 on 2026-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
