# Generated by Django 5.2.17 on 2026-09-14 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthSigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_key_encrypted', models.BinaryField()),
                ('public_key_pem', models.TextField()),
                ('algorithm', models.CharField(default='RS256', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=64)),
                ('application_type', models.CharField(choices=[('confidential_web', 'Confidential web application')], default='confidential_web', max_length=32)),
                ('redirect_uris', models.JSONField(default=list)),
                ('post_logout_redirect_uris', models.JSONField(blank=True, default=list)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=2048)),
                ('scope', models.CharField(blank=True, max_length=500)),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(default='S256', max_length=16)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='oauth_provider.oauthclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='oauth_provider.oauthclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
